### Importando bibliotecas necessárias

In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Lendo dados da planilha

In [44]:
"RES. ITUPARARANGA (próx. a Barragem)"
data = pd.read_excel('./Dados_ResItupararanga/dados.xlsx')
dataNotas = data.copy()
dataNotas.head(4)

,Data,TempAmostra,pH,Turbidez,DBO,OD,SolTotais,ColiformesFecais,FosforoTotal,NitrogenioTotal,IQA,Unnamed: 11,Unnamed: 12
0,2019-11-28,23.3,7.69,6.30,2,8.1,50.0,18.75,0.01,0.50,NaN,NaN,NaN
1,2019-09-19,22.5,8.38,4.10,2,8.5,60.0,1.25,0.01,0.50,NaN,NaN,NaN
2,2019-07-10,19.3,6.23,2.60,2,7.6,52.0,7.50,0.03,0.60,NaN,NaN,NaN
3,2019-05-16,22.8,6.45,3.46,3,5.8,100.0,1.25,0.02,0.65,NaN,NaN,1.25

### Cálculo da nota de OD (Oxigênio Dissolvido) [% de saturação]

Os dados de OD vieram em mg/L, portanto é necessário fazer a coversão.

In [45]:
altitude = 840
EqGeralOD = 14.62 - (0.3898 * dataNotas["TempAmostra"]) +\
             (0.006969 * (dataNotas["TempAmostra"] ** 2) -\
              (0.00005896 * (dataNotas["TempAmostra"] ** 3))) * ((1 - 0.0000228675 * altitude)) ** 5,167

OD_saturado = dataNotas["OD"] * 100 / EqGeralOD[0]

i = 0
resultadoOD = []

for i in range(len(OD_saturado)):
    
    if OD_saturado[i] > 140:
        resultadoOD.append(47)
        
    elif OD_saturado[i] > 100:
        resultadoOD.append(((2.9 * OD_saturado[i])- (0.02496 * OD_saturado[i] ** 2) +\
                            (5.60919 * 0.00001 * (OD_saturado[i] ** 3))) + 3)
        
    elif OD_saturado[i] > 85:
        resultadoOD.append((3.7745 * (OD_saturado[i] ** 0.704889)) + 3)
        
    elif OD_saturado[i] > 50:
        resultadoOD.append(((-1.166 * OD_saturado[i]) + (0.058 * (OD_saturado[i] ** 2)) -\
                             (3.803435 * 0.0001 * (OD_saturado[i] ** 3))) + 3)
        
    else:
        resultadoOD.append(((0.34 * OD_saturado[i]) + (0.008095 * (OD_saturado[i] ** 2)) +\
                             (1.35252 * 0.00001 * (OD_saturado[i] ** 3))) + 3)
        
dataNotas["OD"] = resultadoOD

### Cálculo da nota de Temperatura da Amostra [°C]

Considera-se que a diferença de temperatura é zero, uma vez que nossos
cursos hídricos não apresentam grande diferença a montante e a jusante do ponto
escolhido, sendo assim o subíndice é considerado igual a 94.

In [46]:
dataNotas["TempAmostra"] = 94

### Cálculo da nota de Coliformes [NPM/100mL]

In [47]:
i = 0
resultadoColiformes = []

for i in range(len(dataNotas["ColiformesFecais"])):
    
    if dataNotas["ColiformesFecais"][i] == 0:
        resultadoColiformes.append(100)
        
    else:
        coli10 = np.log10(dataNotas["ColiformesFecais"][i])
        
        if coli10 > 5:
            resultadoColiformes.append(3)
            
        elif coli10 > 1:
            resultadoColiformes.append(100 - (37.2 * coli10) + (3.60743 * (coli10 ** 2)))
            
        else:
            resultadoColiformes.append(100 - (33 * coli10))

dataNotas["ColiformesFecais"] = resultadoColiformes

### Cálculo da nota de pH

In [48]:
i = 0
resultadopH = []

for i in range(len(dataNotas["pH"])):
    
    if dataNotas["pH"][i] <= 2:
        resultadopH.append(2)
        
    elif dataNotas["pH"][i] <= 4:
        resultadopH.append(13.6 - (10.6 * dataNotas["pH"][i]) + (2.4364 * (dataNotas["pH"][i] ** 2)))
        
    elif dataNotas["pH"][i] <= 6.2:
        resultadopH.append(155.5 - (77.36 * dataNotas["pH"][i]) + (10.2481  * (dataNotas["pH"][i] ** 2)))
        
    elif dataNotas["pH"][i] <= 7:
        resultadopH.append(-657.2 + (197.38 * dataNotas["pH"][i]) - (12.9167  * (dataNotas["pH"][i] ** 2)))
        
    elif dataNotas["pH"][i] <= 8:
        resultadopH.append(-427.8 + (142.05 * dataNotas["pH"][i]) - (9.695  * (dataNotas["pH"][i] ** 2)))
    
    elif dataNotas["pH"][i] <= 8.5:
        resultadopH.append(216 - (16 * dataNotas["pH"][i]))
        
    elif dataNotas["pH"][i] <= 9:
        resultadopH.append(1415823 * (np.exp(-1.1507 * dataNotas["pH"][i])))
        
    elif dataNotas["pH"][i] <= 10:
        resultadopH.append(228 - (27 * dataNotas["pH"][i]))
        
    elif dataNotas["pH"][i] <= 12:
        resultadopH.append(633 - (106.5 * dataNotas["pH"][i]) + (4.5  * (dataNotas["pH"][i] ** 2)))
        
    else:
        resultadopH.append(3)

dataNotas["pH"] = resultadopH

### Cálculo da nota de DBO (Demanda Bioquímica de Oxigênio) [mg/L]

In [49]:
i = 0
resultadoDBO = []

for i in range(len(dataNotas["DBO"])):
    
    if dataNotas["DBO"][i] <= 5:
        resultadoDBO.append(99.96 * np.exp((-0.1232728) * dataNotas["DBO"][i]))
    
    elif dataNotas["DBO"][i] <= 15:
        resultadoDBO.append(104.67 - (31.5463 * np.log(dataNotas["DBO"][i])))
        
    elif dataNotas["DBO"][i] <= 30:
        resultadoDBO.append(4394.91 * (dataNotas["DBO"][i] ** (-1.99809)))
        
    else:
        resultadoDBO.append(2)
        
dataNotas["DBO"] = resultadoDBO

### Cálculo da nota de Nitrogênio Total [mg/L]

In [50]:
i = 0
resultadoNT = []

for i in range(len(dataNotas["NitrogenioTotal"])):  
    
    if dataNotas["NitrogenioTotal"][i] <= 10:
        resultadoNT.append(100 - (8.169 * dataNotas["NitrogenioTotal"][i]) +\
                           (0.3059 * (dataNotas["NitrogenioTotal"][i] ** 2)))
    
    elif dataNotas["NitrogenioTotal"][i] <= 60:
        resultadoNT.append(101.9 - 23.1023 * np.log(dataNotas["NitrogenioTotal"][i]))
        
    elif dataNotas["NitrogenioTotal"][i] <= 100:
        resultadoNT.append(159.3148 * 2.7828 ** (dataNotas["NitrogenioTotal"][i] * (-0.512842)))
        
    else:
        resultadoNT.append(1)
        
dataNotas["NitrogenioTotal"] = resultadoNT

### Cálculo da nota de Fósforo Total [mg/L]

É necessário converter para fosfato. O fator de conversão é 3.066

In [51]:
i = 0
resultadoFT = []

for i in range(len(dataNotas["FosforoTotal"])):
    PO4 = dataNotas["FosforoTotal"][i] * 3.066
    
    if dataNotas["FosforoTotal"][i] <= 1:
        resultadoFT.append(99 * np.exp((-0.91629 * PO4)))
    
    elif dataNotas["FosforoTotal"][i] <= 5:
        resultadoFT.append(57.6 - 20.178 * PO4 + 2.1326 * (PO4 ** 2))
        
    elif dataNotas["FosforoTotal"][i] <= 10:
        resultadoFT.append(19.8 * np.exp((-0.13544 * PO4)))
        
    else:
        resultadoFT.append(1)
        
dataNotas["FosforoTotal"] = resultadoFT

### Cálculo da nota de Turbidez [UFT]

In [52]:
i = 0
resultadoTurbidez = []

for i in range(len(dataNotas["Turbidez"])):
    
    if dataNotas["Turbidez"][i] <= 25:
        resultadoTurbidez.append(100 - 2.67 * dataNotas["Turbidez"][i] + 0.03775 * (dataNotas["Turbidez"][i] ** 2))
    
    elif dataNotas["Turbidez"][i] <= 100:
        resultadoTurbidez.append(84.76 * np.exp(-0.016206 * dataNotas["Turbidez"][i]))
        
    else:
        resultadoTurbidez.append(5)
        
dataNotas["Turbidez"] = resultadoTurbidez

### Cálculo da nota de Sólidos Totais [mg/L]

In [53]:
i = 0
resultadoST = []

for i in range(len(dataNotas["SolTotais"])):
    
    if dataNotas["SolTotais"][i] <= 150:
        resultadoST.append(79.75 + 0.166 * dataNotas["SolTotais"][i] - 0.001088 * (dataNotas["SolTotais"][i] ** 2))
    
    elif dataNotas["SolTotais"][i] <= 500:
        resultadoST.append(101.67 - 0.13917 * dataNotas["SolTotais"][i])
        
    else:
        resultadoST.append(32)
        
dataNotas["SolTotais"] = resultadoST

### Cálculo do IQA

In [54]:
pesos = {
    "OD" : 0.17,
    "ColiformesFecais" : 0.15,
    "pH" : 0.12,
    "DBO" : 0.1,
    "FosforoTotal" : 0.1,
    "TempAmostra" : 0.1,
    "NitrogenioTotal" : 0.1,
    "Turbidez" : 0.08,
    "SolTotais" : 0.08
}

dataNotas["IQA"] = 0
for key in pesos:
    dataNotas["IQA"] += dataNotas[key] * pesos[key]
    
dataNotas.head(4)

,Data,TempAmostra,pH,Turbidez,DBO,OD,SolTotais,ColiformesFecais,FosforoTotal,NitrogenioTotal,IQA,Unnamed: 11,Unnamed: 12
0,2019-11-28,94,91.240011,84.677298,78.118313,98.361502,85.330000,58.490309,96.257452,95.991975,86.481161,NaN,NaN
1,2019-09-19,94,81.920000,89.687578,78.118313,99.206708,85.793200,96.801970,96.257452,95.991975,91.691072,NaN,NaN
2,2019-07-10,94,71.142815,93.313190,78.118313,88.771417,85.440048,71.122978,90.998179,95.208724,84.429506,NaN,NaN
3,2019-05-16,94,78.533988,91.213728,69.058344,73.963054,85.470000,96.801970,93.590880,94.819393,85.799653,NaN,1.25

In [55]:
dataNotas.to_excel("./Dados_ResItupararanga/IQA_Calculado.xlsx")